### ISSUE TITLE
Error while importing arviz from provided conda environment

### ISSUE THREAD

**Issue by FernanOrtega** [aloctavodia/BAP#66]
I just started reading your book and I used the env.yml file to create the conda environment with the required packages.

Unfortunately, importing arviz package results in the following error:

```python
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-2-d3b40e9507e8> in <module>
      3 import pandas as pd
      4 from scipy import stats
----> 5 import arviz as az

~\Anaconda3\envs\bap\lib\site-packages\arviz\__init__.py in <module>
     20     _log.addHandler(handler)
     21 
---> 22 from .data import *
     23 from .plots import *
     24 from .stats import *

~\Anaconda3\envs\bap\lib\site-packages\arviz\data\__init__.py in <module>
      1 """Code for loading and manipulating data structures."""
----> 2 from .inference_data import InferenceData
      3 from .io_netcdf import load_data, save_data
      4 from .datasets import load_arviz_data, list_datasets, clear_data_home
      5 from .base import numpy_to_data_array, dict_to_dataset

~\Anaconda3\envs\bap\lib\site-packages\arviz\data\inference_data.py in <module>
      1 """Data structure for using netcdf groups with xarray."""
----> 2 import netCDF4 as nc
      3 import xarray as xr
      4 
      5 

~\Anaconda3\envs\bap\lib\site-packages\netCDF4\__init__.py in <module>
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__, __pdoc__

include\membuf.pyx in init netCDF4._netCDF4()

AttributeError: type object 'netCDF4._netCDF4._MemBuf' has no attribute '__reduce_cython__'

```

Do we need to install anything else? I work on Windows 10 with Python 3.6.

Thanks in advance.

**Comment by canyon289** [comment]
Hi @FernanOrtega This is a shot in the dark but trry upgrading to to python 3.7, It seems there some underlying issues with the netcdf or python and a new version of python might help

**Comment by FernanOrtega** [comment]
Yes!, that is, thanks.

Maybe it might be a good idea to update the YAML file with the definition of the Conda environment.

**Comment by roumail** [comment]
+1 For updating the conda environment specification. I ended up specifying strict channel priority to speed conda solving the environment for hours. I also updating to python 3.7 but in the end after hours conda gave up citing package conflicts

excerpt from log
```
....

ipykernel

Package freetype conflicts for:
graphviz=2.38.0 -> cairo[version='>=1.16.0,<1.17.0a0'] -> freetype[version='2.7.*|>=2.10.4,<3.0a0|>=2.8.1,<2.9.0a0|>=2.8,<2.9.0a0']
graphviz=2.38.0 -> freetype[version='2.5.*|2.6.*|2.7|2.7.*|2.7|2.8.1|>=2.9.1,<3.0a0']

Package pyopenssl conflicts for:
requests -> urllib3[version='>=1.21.1,<1.27'] -> pyopenssl[version='>=0.14']
pyopenssl
conda -> pyopenssl[version='>=16.2.0']
urllib3 -> pyopenssl[version='>=0.14']

Package tbb conflicts for:
numpy=1.14.2 -> mkl -> tbb=2021
blas -> mkl -> tbb=2021

Package yaml conflicts for:
ruamel_yaml -> yaml[version='>=0.1.7,<0.2.0a0|>=0.2.5,<0.3.0a0|>=0.2.2,<0.3.0a0']
conda -> ruamel_yaml[version='>=0.11.14,<0.16'] -> yaml[version='>=0.1.7,<0.2.0a0|>=0.2.5,<0.3.0a0|>=0.2.2,<0.3.0a0']
yaml

Package libedit conflicts for:
sqlite -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0|>=3.1.20191231,<3.2.0a0']
python=3.7 -> sqlite[version='>=3.33.0,<4.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0|>=3.1.20191231,<3.2.0a0']

Package prompt-toolkit conflicts for:
ipython=7 -> prompt_toolkit[version='>=2.0.0,<4,!=3.0.0,!=3.0.1'] -> prompt-toolkit[version='>=3.0.10,<3.0.11.0a0|>=3.0.11,<3.0.12.0a0|>=3.0.13,<3.0.14.0a0|>=3.0.14,<3.0.15.0a0|>=3.0.16,<3.0.17.0a0|>=3.0.17,<3.0.18.0a0|>=3.0.18,<3.0.19.0a0|>=3.0.19,<3.0.20.0a0|>=3.0.20,<3.0.21.0a0|>=3.0.21,<3.0.22.0a0|>=3.0.22,<3.0.23.0a0|>=3.0.9,<3.0.10.0a0|>=3.0.8,<3.0.9.0a0|>=3.0.7,<3.0.8.0a0|>=3.0.6,<3.0.7.0a0|>=3.0.5,<3.0.6.0a0|>=3.0.4,<3.0.5.0a0']
ipython=7 -> prompt-toolkit[version='!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0|>=2.0.0,!=3.0.0,!=3.0.1,<3.1.0']

Package libgfortran5 conflicts for:
blas -> libgfortran-ng -> libgfortran5[version='10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|11.1.0|11.1.0|11.1.0|11.1.0|11.1.0|11.2.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.3.0.*|8.5.0|8.5.0|8.5.0|8.5.0|8.4.0.*',build='h0ffbd86_8|h0ffbd86_9|h62347ff_4|h62347ff_5|h62347ff_8|h62347ff_9|h62347ff_11|hb56cab1_4|hb56cab1_5|hb56cab1_6|hb56cab1_7|hb56cab1_10|h6c583b3_5|h6c583b3_7|h6c583b3_8|h5c6108e_9|h5c6108e_11|h5c6108e_10|h5c6108e_8|h6c583b3_6|h6c583b3_4|hb56cab1_11|hb56cab1_9|hb56cab1_8|h62347ff_10|h62347ff_7|h62347ff_6|h0ffbd86_11|h0ffbd86_10']
blas -> libgfortran5[version='>=9.3.0|>=9.4.0']

Package graphviz conflicts for:
graphviz=2.38.0
python-graphviz=0.8.4 -> graphviz


```

**Comment by roumail** [comment]
What finally worked for me was the following:

```
conda create -y -n bap2 python=3.6 
conda activate bap2
conda install -y ipython=7.0 jupyter=1.0 numpy=1.14.2 pymc3=3.6 scipy=1.1 pandas=0.23.4 matplotlib=3.0.2 seaborn=0.9.0
pip install arviz==0.3.1
```
